import { GameCategory, GameSessionStatus, PlayerType } from './index';

// Firestore collection interfaces
export interface Game {
  uid: string; // auto-generated by Firestore, immutable
  gameId: string; // 'tic-tac-toe', 'connect4', etc.
  name: string;
  description: string;
  category: GameCategory;
  icon: string; // emoji
  isActive: boolean;
  createdAt: string; // ISO 8601 UTC
  lastUpdatedAt: string; // ISO 8601 UTC
}

export interface GameSession {
  uid: string; // auto-generated by Firestore, immutable
  gameUid: string; // reference to games collection
  anonymousUserUid: string; // Firebase Auth UID from anonymous sign-in
  status: GameSessionStatus;
  winner: PlayerType;
  startedAt: string; // ISO 8601 UTC
  endedAt: string; // ISO 8601 UTC
  createdAt: string; // ISO 8601 UTC
  lastUpdatedAt: string; // ISO 8601 UTC
}

export interface AnonymousUser {
  uid: string; // Firebase Auth UID from anonymous sign-in, immutable
  gamesPlayed: number;
  lastActiveAt: string; // ISO 8601 UTC
  createdAt: string; // ISO 8601 UTC
}

export interface GlobalStats {
  totalGamesPlayed: number;
  totalPlayers: number;
  totalMatches: number;
  lastUpdatedAt: string; // ISO 8601 UTC
}

export interface GameStats {
  uid: string; // auto-generated by Firestore, immutable
  gameUid: string; // reference to games collection
  totalGamesPlayed: number;
  averagePlayTime: number; // minutes
  winRate: {
    player: number;
    ai: number;
    draw: number;
  };
  lastUpdatedAt: string; // ISO 8601 UTC
}
